name: Update Data
on:
  schedule:
    # Run every 4 hours, at the 35th minute
    - cron: '35 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update:
    name: Update data
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      uses: josStorer/get-current-time@v2
      id: current-time
      with:
        # Versioning is current date
        # Intentionally without leading zeroes
        # to comply with semver
        format: "YYYY.M.D+HHmm"
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - name: Run Tests
      run: python -m pytest test/
    # TODO: Use pygit instead of an older copy.
    - name: Update dataset
      id: generate
      run: |
        cp data.csv /tmp/data.csv
        echo "changelog<<__EOL__" > "$GITHUB_OUTPUT"
        python -m src /tmp/data.csv | tee -a "$GITHUB_OUTPUT"
        echo "__EOL__" >> "$GITHUB_OUTPUT"
    - uses: stefanzweifel/git-auto-commit-action@v4
      name: Commit Updates
      id: commit
      with:
        commit_message: |
          Update Total Expense Ratios

          Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs/${{ github.job }}
          Workflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/workflow

          Changes in TER (Direct Plans only):

          ${{steps.generate.outputs.changelog}}
        commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
        file_pattern: '*.csv'
        tagging_message: 'v${{ steps.current-time.outputs.formattedTime }}'
    - name: Create GitHub Release (TER Changes)
      run: |
        gh release create 'v${{ steps.current-time.outputs.formattedTime }}' --latest --notes 'Changes for Direct Plans:
        ${{steps.generate.outputs.changelog}}' data.csv
      # Run this if changes were detected, and changelog was not empty
      if: steps.commit.outputs.changes_detected == 'true' && contains(steps.generate.outputs.changelog, 'TER')
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Create GitHub Release (No Direct Plan Changes)
      run: |
        gh release create 'v${{ steps.current-time.outputs.formattedTime }}' --latest --notes 'No TER changes in any Direct Plans' data.csv
      # Run this if changes were detected, and changelog was empty.
      if: steps.commit.outputs.changes_detected == 'true' && ( ! contains(steps.generate.outputs.changelog, 'TER') )
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Post to Mastodon
      run: echo '${{steps.generate.outputs.changelog}}' | python src/toot.py
      if: steps.commit.outputs.changes_detected == 'true' && contains(steps.generate.outputs.changelog, 'TER')