name: Update Data
on:
  schedule:
    # Run every 4 hours, at the 35th minute
    - cron: '35 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update:
    name: Update data
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      uses: josStorer/get-current-time@v2
      id: current-time
      with:
        # Versioning is current date
        # Intentionally without leading zeroes
        # to comply with semver
        format: "YYYY.M.D+HHmm"
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - name: Run Tests
      run: python -m pytest test/
    # TODO: Use pygit instead of an older copy.
    - name: Update dataset
      id: generate
      run: |
        cp data.csv /tmp/data.csv
        echo "changelog<<__EOL__" > "$GITHUB_OUTPUT"
        python -m src /tmp/data.csv | tee -a "$GITHUB_OUTPUT"
        echo "__EOL__" >> "$GITHUB_OUTPUT"
    - uses: stefanzweifel/git-auto-commit-action@v4
      name: Commit Updates
      id: scheduled_commit_action
      with:
        commit_message: |
          Update Total Expense Ratios

          ${{steps.generate.outputs.changelog}}
        commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
        file_pattern: '*.csv'
        tagging_message: 'v${{ steps.current-time.outputs.formattedTime }}'
      if: ${{ github.event_name == 'schedule' }}
    - name: Create GitHub Release
      run: |
        gh release create 'v${{ steps.current-time.outputs.formattedTime }}' --latest --notes '${{steps.generate.outputs.changelog}}' data.csv
      if: steps.scheduled_commit_action.outputs.changes_detected == 'true'
      env:
        GH_TOKEN: ${{ github.token }}
    # Do not tag if this is a non-scheduled run
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: |
          Update Total Expense Ratios

          ${{steps.generate.outputs.changelog}}
        commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
        file_pattern: '*.csv'
      if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch'}}